### ISSUE TITLE
Formatting of Returned Text

### ISSUE THREAD

**Issue by asafdari-boop** [jucasoliveira/terminalGPT#13]
When you request a sample python script newlines and formatting does not return correctly-- entire flask script could be on one line.

**Comment by jucasoliveira** [comment]
> When you request a sample python script newlines and formatting does not return correctly-- entire flask script could be on one line. 

Thanks for the feedback.
I believe it will be down to the prompt when getting back the result. I'll work on it and make improvements on the return answer

**Comment by jucasoliveira** [comment]
closing it, if the issue persist feel free to reopen.
