### ISSUE TITLE
Unexpected Token when installing

### ISSUE THREAD

**Issue by Calibr3-IO** [jucasoliveira/terminalGPT#14]
When running the command `npx terminalgpt` it returns unexpected token.

**Comment by jucasoliveira** [comment]
> When running the command `npx terminalgpt` it returns unexpected token.

Can you copy the prompt and paste here for us ?

**Comment by segevido** [comment]
```
$ npx terminalgpt
npx: installed 51 in 1.14s
Unexpected token .
```

**Comment by ostapkob** [comment]
I have the same problem:
`npx terminalgpt chat
npx: installed 51 in 7.946s
Unexpected token .`

**Comment by Jamessigur** [comment]
такая же проблема,подскажите как решить?

**Comment by ma3oun** [comment]
same problem on ubuntu 20.04 after `sudo apt install npm;npx terminalgpt`

**Comment by naveenbish** [comment]
I was also getting the same error but I have resolved it by update the node and npm version using below Commands
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
sudo n latest
npm install -g npm@9.3.1
npx terminalgpt
npx terminalgpt chat
#Enter your new api key.
