### ISSUE TITLE
When running npx terminalgpt chat command  in 

### ISSUE THREAD

**Issue by dennissolver** [jucasoliveira/terminalGPT#15]
When running npx terminalgpt chat command in command prompt or PowerShell terminals,  get "Something went wrong!!  error: request failed with status code 401 Something went wrong!" after entering API key

**Comment by ikhwanizao** [comment]
I am having the same error as well. I have tried changing the API secret key but to now avail.

**Comment by jucasoliveira** [comment]
Thanks for the feedbacks. I don't have a way to test on powershell atm, but I'll create a way to create a check log where users can copy and paste here. I believe it would add more context and make it able to fix the issue.

In the meanwhile , any PR solving this problem will be very welcome .

**Comment by thanhsonng** [comment]
This happens in zsh shell on macOS as well. Maybe it's not a Powershell problem

**Comment by thanhsonng** [comment]
I think I found the problem. Inside `apiKeyPrompt` we are returning the encrypted key, not the original one. I will open a PR for this

<img width="1042" alt="Screenshot 2023-01-07 at 10 51 32 a m" src="https://user-images.githubusercontent.com/28614996/211146580-c48de037-18b5-426a-8fac-bdc54110afde.png">

**Comment by dennissolver** [comment]
Ok thanks


Dennis McMahon

CEO, MCM GreenMan Group / Global Buildtech
www.global-buildtech.weebly.com

Ph/ WhatsApp +60169839715

E: ***@***.***

LinkedIn: www.linkedin.com/in/denniskl

**Comment by jucasoliveira** [comment]
> I think I found the problem. Inside `apiKeyPrompt` we are returning the encrypted key, not the original one. I will open a PR for this
> 
> 
> 
> <img width="1042" alt="Screenshot 2023-01-07 at 10 51 32 a m" src="https://user-images.githubusercontent.com/28614996/211146580-c48de037-18b5-426a-8fac-bdc54110afde.png">
> 
> 

Thanks for find this! I'll be reviewing your PR asap:)
