### ISSUE TITLE
how i can uninstall terminagpt?

### ISSUE THREAD

**Issue by mxcdh** [jucasoliveira/terminalGPT#29]
I trying:
```
npm uninstall -g terminalgpt
```

But is not working.

**Comment by glytch3** [comment]
'npx terminalgpt' doesn't install the terminalgpt package, instead it downloads the package to your pc and directly executes it from the cache. 

You can find the package using
> ls ~/.npm/_npx/*/node_modules

To delete the package, you can use 
> rm -r ~/.npm/_npx/*/node_modules/terminalgpt

**Comment by jucasoliveira** [comment]
@glytch3 thanks for explaining, I'll add it on README
