### ISSUE TITLE
On the contrary of the online interface, multilanguage doesnt work

### ISSUE THREAD

**Issue by olivierpons** [jucasoliveira/terminalGPT#37]
On the contrary of the online interface, multilanguage doesnt work

**To Reproduce**
1. try `give me a sample of EULA for a website selling internet services`
2. try the same in french: `donne moi un exemple de CLUF pour un site qui vend des services en ligne`

You get both answers in english.

**Expected behavior**
An answer in english, another in french

**Comment by jucasoliveira** [comment]
Nice catch @olivierpons. This is something worth looking for

**Comment by jucasoliveira** [comment]
![Screenshot 2023-03-06 at 22 21 23](https://user-images.githubusercontent.com/11979969/223255554-dd529902-5d0c-47bc-ba34-de551d366fd5.png)
Terminal GPT now supports multilanguage
