### ISSUE TITLE
Weird outputs on Mac & Windows

### ISSUE THREAD

**Issue by bellacapilla** [jucasoliveira/terminalGPT#41]
**Describe the bug**
Terminalgpt is currently returning some weird outputs. I know this is something new because I made a video about this library on the 18th and it was running perfectly. However, today I noticed I couldn't run it from root anymore (as I show in my Youtube video) and had to reinstall in a new folder. Ok... Reinstall.. New API Key, no problem. But still.. the answers I'm getting are really weird and not like before.

I just tested both on Mac and Windows. Had to reinstall on mac too, but I was able to install directly in root. On Mac it doesn't give you random sentences before the answer, but they are nonsense, worse than on windows.

**To Reproduce**
1. Reinstalled
2. Add token
3. Ask anything. After 2 questions, the problems start.

**Expected behavior**
Well.. I expected to work nicely as it was working earlier :D Specially now that I made a video about this tool.

**Screenshots**
The whole conversation on windows:
<img width="917" alt="Screenshot 2023-01-24 133255" src="https://user-images.githubusercontent.com/28533448/214292820-f0ced6ea-212e-41f2-923e-e7ec07c0cd32.png">

The whole conversation on mac:
<img width="787" alt="Bildschirmfoto 2023-01-24 um 13 40 55" src="https://user-images.githubusercontent.com/28533448/214294398-26db3e09-5c56-4da7-a178-25245128981f.png">

**Desktop (please complete the following information):**
 - OS: Windows & macOS Monterey
 - Terminnal : powershell / Terminal

**Additional context**
I'm a big fan of this library and I hope we can figure this out! :) I wanted to make more videos about it today, and that's when I faced this current issue. Is it just me?

**Comment by jucasoliveira** [comment]
Hi @bellacapilla thanks for informing this issue! I'll be check the context and I'll see what's happening.

I've changed the way it uses context, and I might have a fix for the next version later today or early tomorrow.
