### ISSUE TITLE
Command 'tgpt' not found

### ISSUE THREAD

**Issue by sportflier** [jucasoliveira/terminalGPT#43]
Per the readme, I've installed using the yarn option. No errors are indicated during the installation. However, when I run **tgpt chat** or **tgpt** at the command line, I get the error **Command 'tgpt' not found**.

This behavior is the same when installing on Windows as well as WSL (Ubuntu 22.x).

_Yarn list_ shows **terminalgpt@1.0.9** installed.

Hopefully just user error on my part.

**Comment by jucasoliveira** [comment]
Hi @sportflier how are you? Thanks for the report, I've checked and the script to add using yarn is wrong, I'll be putting forward a change on README for you properly install using it.

The correct script is `yarn global add terminalgpt`

![image](https://user-images.githubusercontent.com/11979969/216246024-fabb3d9e-0dfe-4c5d-8d31-b2c676fd9662.png)

**Comment by sportflier** [comment]
@jucasoliveira I just tried again with the syntax provided here, I'm still having the same problem:
![pwsh-tgpt](https://user-images.githubusercontent.com/302203/216355978-7fce74fe-2a01-4baf-b6d8-28aec6bb1b84.png)

WSL Ubuntu 22:
![wsl-ubuntu-tgpt](https://user-images.githubusercontent.com/302203/216357683-c5c61213-2a12-481c-86c4-364dd6c3729d.png)
