### ISSUE TITLE
Error code 429

### ISSUE THREAD

**Issue by Jacoba1100254352** [jucasoliveira/terminalGPT#47]
I tried the various methods to install, all installed seemingly without issue, but upon running in each on my MacOS 13.2 it gave me the error:

```
Thinking...Something went wrong!!! Error: Request failed with status code 429
Something went wrong!! Error: Something went wrong!
1 Something went wrong!! Error: Something went wrong!
```

**Comment by CerfMetal** [comment]
Same! On macos Ventura 13.0. Had to install using sudo but getting error code 429 : 
`✔ You:  … hello
          ■■▶ Thinking...Something went wrong!!! Error: Request failed with status code 429
Something went wrong!! Error: Something went wrong!
1 Something went wrong!! Error: Something went wrong!`

**Comment by metcalsr28** [comment]
I'm encountering this issue as well on Manjaro after installing with yarn.

**Comment by victorminne** [comment]
got the same while running tgpt on a docker container with ubuntu latest.

**Comment by jucasoliveira** [comment]
- Closing because of new version, please reopen if you face the same error again
