### ISSUE TITLE
" I'm sorry, I don't understand the question. "

### ISSUE THREAD

**Issue by JPLACLAU** [jucasoliveira/terminalGPT#49]
**Describe the bug**
I'm sorry, I don't understand the question.

**To Reproduce**
For most of the questions I asked, it always answers the same thing:
" I'm sorry, I don't understand the question. ".

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/13803869/217397374-602f4399-d629-4f8b-85b0-b91d87dc459f.png)

**Desktop (please complete the following information):**
 - OS: wsl2 ubuntu on win10
 - Terminnal : [zsh] and tmux

**Additional context**
I just installed this app and trying it for the first time.

**Comment by jucasoliveira** [comment]
Closing because this is the old version of the application, please test on the new versions, if the issue continues, please reopen it :)
