### ISSUE TITLE
Can't interact with gpt

### ISSUE THREAD

**Issue by dannybotek** [jucasoliveira/terminalGPT#53]
Hi! Whenever I run

sudo tgpt chat

and try to enter a command, I get this error

■■▶ Thinking...Something went wrong!!! Error: Request failed with status code 429
Something went wrong!! Error: Something went wrong!
1 Something went wrong!! Error: Something went wrong!
? Try again? › - Use arrow-keys. Return to submit.
❯   Yes
    No - exit

Any ideas? Thanks!

**Comment by FrancescoDesiderato** [comment]
> Hi! Whenever I run
> 
> sudo tgpt chat
> 
> and try to enter a command, I get this error
> 
> ■■arrow_forward Thinking...Something went wrong!!! Error: Request failed with status code 429 Something went wrong!! Error: Something went wrong! 1 Something went wrong!! Error: Something went wrong! ? Try again? › - Use arrow-keys. Return to submit. ❯ Yes No - exit
> 
> Any ideas? Thanks!
