### ISSUE TITLE
CRITICAL: ReferenceError: options is not defined. terminalgpt/bin/utils.js:100:42

### ISSUE THREAD

**Issue by joseito-terence** [jucasoliveira/terminalGPT#64]
**Describe the bug**
ReferenceError: options is not defined. (terminalgpt/bin/utils.js:100:42)

**To Reproduce**
1. npx terminalgpt chat
2. Try Again (Yes)

**Expected behavior**
Should try Again.

**Screenshots**
```
/home/.../.npm/_npx/0e1ec426b0185841/node_modules/terminalgpt/bin/utils.js:100
        generateResponse(apiKey, prompt, options, response);
                                         ^

ReferenceError: options is not defined
    at generateResponse (/home/joseito/.npm/_npx/0e1ec426b0185841/node_modules/terminalgpt/bin/utils.js:100:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Terminnal :  zsh

**Comment by benzhemin** [comment]
Same issue, not working

**Comment by petrgazarov** [comment]
This issue should be closed. It was fixed via https://github.com/jucasoliveira/terminalGPT/pull/66
