### ISSUE TITLE
ReferenceError: options is not defined

### ISSUE THREAD

**Issue by ahmed192a** [jucasoliveira/terminalGPT#65]
**Describe the bug**
when the utils ask to try again or not it calls the "generateResponse" and pass four parametes instead of three. Also the passed parameter "options" isn't defined.
https://github.com/jucasoliveira/terminalGPT/blob/90cac44af4f83664a2a0f96e4ef6061de72b74f4/bin/utils.js#L100

**To Reproduce**
1. use a large prompt and wait fot the terminal to asks you to try again
2. choose Yes
3. See the error

**Expected behavior**
Regenerate the respone in case choosed "yes" or wai for another prompt for user incase choosed "No".

**Screenshots**
![Screenshot from 2023-04-06 14-35-01](https://user-images.githubusercontent.com/42156372/230380489-453371cc-b6ab-4463-9d9a-660f07810f1c.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Terminnal :  sh

**Comment by petrgazarov** [comment]
Fixed via https://github.com/jucasoliveira/terminalGPT/pull/66
