### ISSUE TITLE
can't install on Windows for git bash or powershell

### ISSUE THREAD

**Issue by calebgibney** [jucasoliveira/terminalGPT#79]
fails to install with this output:

npm ERR! code 1
npm ERR! path C:\Users\my_username\AppData\Roaming\npm\node_modules\terminalgpt
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c tsc
npm ERR! 'tsc' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\my_username\AppData\Local\npm-cache\_logs\2023-09-23T20_45_34_003Z-debug-0.log

**To Reproduce**
inside git bash or cmd or powershell, run this command:
npm -g install terminalgpt

**Desktop (please complete the following information):**
Windows 10 
 Using git bash or powershell

**Comment by lucasgooliveira** [comment]
Hi @calebgibney , can you give the logs of the error ? It would help a lot , as I don't have a Windows machine.

**Comment by calebgibney** [comment]
[2023-10-01T15_44_41_224Z-debug-0.log](https://github.com/jucasoliveira/terminalGPT/files/12777523/2023-10-01T15_44_41_224Z-debug-0.log)

@lucasgooliveira thank you very much for willingness to investigate!

**Comment by squirrelroad** [comment]
The above is because typescript is not installed yet, so it could not call `tsc` to compile.
Maybe adding typescript to the dependency helps?

**Describe the bug** 
Compile error -- pasted below

**To Reproduce** 
- have nodejs installed
`npm install -g terminalgpt`

**Expected behavior**
npm installed without issues  

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Terminnal : cwd

**Additional context**
Add any other context about the problem here.

````
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\squirrelroad\\.conda\\envs\\ter\\node_modules\\terminalgpt',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\squirrelroad\.conda\envs\ter\node_modules\terminalgpt\node_modules\compromise\src\2-two\preTagger\compute\tagger'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\squirrelroad\\.conda\\envs\\ter\\node_modules\\terminalgpt\\node_modules\\compromise\\src\\2-two\\preTagger\\compute\\tagger'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\squirrelroad\\.conda\\envs\\ter\\node_modules\\terminalgpt\\node_modules\\compromise',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\squirrelroad\.conda\envs\ter\node_modules\terminalgpt\node_modules\compromise\src\2-two\preTagger\methods\transform\nouns'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\squirrelroad\\.conda\\envs\\ter\\node_modules\\terminalgpt\\node_modules\\compromise\\src\\2-two\\preTagger\\methods\\transform\\nouns'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 2
npm ERR! path C:\Users\squirrelroad\.conda\envs\ter\node_modules\terminalgpt
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c tsc
npm ERR! src/utils.ts(17,5): error TS2322: Type 'TerminalRenderer' is not assignable to type 'Renderer<never>'.
npm ERR!   The types of 'options.renderer' are incompatible between these types.
npm ERR!     Type 'Omit<_Renderer, "constructor"> | null | undefined' is not assignable to type 'Renderer<never> | undefined'.
npm ERR!       Type 'null' is not assignable to type 'Renderer<never> | undefined'.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\squirrelroad\AppData\Local\npm-cache\_logs\2023-10-05T09_13_08_580Z-debug-0.log
````


I think =types/marked-terminal` is not compatible with Windows? if there's alternative to test by temporarily removing this package?

Kind regards,

**Comment by calebgibney** [comment]
I hope this helps but installing typescript yields new error:

![image](https://github.com/jucasoliveira/terminalGPT/asse
[2023-10-05T18_21_46_573Z-debug-0.log](https://github.com/jucasoliveira/terminalGPT/files/12821844/2023-10-05T18_21_46_573Z-debug-0.log)
ts/60632705/3da73b23-7899-42ab-b96e-3b0f7d6ed85c)

**Comment by lucasgooliveira** [comment]
I've re-tested and found the error, I've update the library to version `1.7.3` and hopefully you'll be able to install it again.
https://github.com/jucasoliveira/terminalGPT/pull/82
