### ISSUE TITLE
npm -g install terminalgpt failed on Mac

### ISSUE THREAD

**Issue by JayZhao** [jucasoliveira/terminalGPT#80]
% npm -g install terminalgpt
npm ERR! code 2
npm ERR! path /opt/homebrew/lib/node_modules/terminalgpt
npm ERR! command failed
npm ERR! command sh -c tsc
npm ERR! src/utils.ts(17,5): error TS2322: Type 'TerminalRenderer' is not assignable to type 'Renderer<never>'.
npm ERR!   The types of 'options.renderer' are incompatible between these types.
npm ERR!     Type 'Omit<_Renderer, "constructor"> | null | undefined' is not assignable to type 'Renderer<never> | undefined'.
npm ERR!       Type 'null' is not assignable to type 'Renderer<never> | undefined'.

npm ERR! A complete log of this run can be found in: /Users/zhaojianyin/.npm/_logs/2023-11-09T13_20_38_483Z-debug-0.log[
[installlog.log](https://github.com/jucasoliveira/terminalGPT/files/13308553/installlog.log)
](url)

**Comment by 1llyaa** [comment]
Same issue but on archlinux
npm install -g terminalgpt@latest

npm ERR! code 2
npm ERR! path /home/illyam/.nvm/versions/node/v20.9.0/lib/node_modules/terminalgpt
npm ERR! command failed
npm ERR! command sh -c tsc
npm ERR! src/utils.ts(17,5): error TS2322: Type 'TerminalRenderer' is not assignable to type 'Renderer<never>'.
npm ERR!   The types of 'options.renderer' are incompatible between these types.
npm ERR!     Type 'Omit<_Renderer, "constructor"> | null | undefined' is not assignable to type 'Renderer<never> | undefined'.
npm ERR!       Type 'null' is not assignable to type 'Renderer<never> | undefined'.

npm ERR! A complete log of this run can be found in: /home/illyam/.npm/_logs/2023-11-13T09_04_13_367Z-debug-0.log
