### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'status')

### ISSUE THREAD

**Issue by AchuAshwath** [jucasoliveira/terminalGPT#85]
C:\>tgpt chat

  **************** Welcome to terminalGPT ****************

     __
<(o )___
 ( ._> /
  `---'

  usage:
    TerminalGPT will ask you to add your OpenAI API key. Don't worry, it will be saved on your machine locally.

    Terminal will prompt you to enter a message. Type your message and press enter.
    Terminal will then prompt you to enter a response. Type your response and press enter.

    To exit, type "exit" and press enter.

    # Commands

√ You:  ... hi
Something went wrong!! TypeError: Cannot read properties of undefined (reading 'status')
? Try again? » - Use arrow-keys. Return to submit.
>   Yes
    No - exit

**Comment by 1llyaa** [comment]
I get same error message

**Comment by jucasoliveira** [comment]
I'll need to seek further investigation on this error.

as of 21/11/2023 I've notice this error using `npx` .

Ive verified I also have the library installed on my local machine and using an old api key.

After removing the package and using `npx` again it prompt the API key 

After adding a new key the package worked as expected:

```
npx terminalgpt chat

  **************** Welcome to terminalGPT ****************

     __
<(o )___
 ( ._> /
  `---'

  usage:
    TerminalGPT will ask you to add your OpenAI API key. Don't worry, it will be saved on your machine locally.

    Terminal will prompt you to enter a message. Type your message and press enter.
    Terminal will then prompt you to enter a response. Type your response and press enter.

    To exit, type "exit" and press enter.

    # Commands


✔ Enter your OpenAI API key: … ***************************************************
✔ You:  … Hello
GPT:
Hello! How can I assist you today? If you have any questions or need help with something, feel free to ask.
? You:  ›
```

I've also did with `tgpt` command and it worked as well:

```
tgpt chat --markdown

  **************** Welcome to terminalGPT ****************

     __
<(o )___
 ( ._> /
  `---'

  usage:
    TerminalGPT will ask you to add your OpenAI API key. Don't worry, it will be saved on your machine locally.

    Terminal will prompt you to enter a message. Type your message and press enter.
    Terminal will then prompt you to enter a response. Type your response and press enter.

    To exit, type "exit" and press enter.

    # Commands


✔ Enter your OpenAI API key: … ***************************************************
✔ You:  … hello
GPT:
Hello! How can I assist you today? If you have any questions or need support with something, feel free to ask.


? You:  ›
```

The troubleshooting I have for now is to uninstall the application:

`npm uninstall -g terminalgpt`

install it again and add a new api key.

Further needed:


`tgpt delete` is not removing the api key, so I'll leave this issue open to solve that
